# Generated by Django 4.1.4 on 2025-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=3, unique=True)),
                ('can_donate_to', models.JSONField(default=list)),
                ('can_receive_from', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Blood Type',
                'verbose_name_plural': 'Blood Types',
            },
        ),
    ]
