# Generated by Django 4.1.4 on 2025-10-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('DONATION_ADDED', 'קליטת תרומת דם'), ('BLOOD_DISPENSED', 'ניפוק דם רגיל'), ('EMERGENCY_DISPENSED', 'ניפוק חירום'), ('DATA_EXPORTED', 'יצוא נתונים'), ('RECORD_VIEWED', 'צפייה ברשומה'), ('INVENTORY_CHECKED', 'בדיקת מלאי'), ('SEARCH_PERFORMED', 'ביצוע חיפוש'), ('BLOOD_EXPIRED', 'סימון מנה כפגה'), ('BATCH_EXPIRED', 'הסרת מנות פגות')], max_length=50),
        ),
    ]
