# Generated by Django 4.1.4 on 2025-09-29 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=3)),
                ('donation_date', models.DateField()),
                ('donor_id', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'מספר ת"ז חייב להכיל 9 ספרות')])),
                ('donor_name', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blood_donations',
                'ordering': ['donation_date'],
            },
        ),
        migrations.DeleteModel(
            name='BloodType',
        ),
    ]
