# Generated by Django 4.1.4 on 2025-09-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank', '0002_blooddonation_delete_bloodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('DONATION_ADDED', 'קליטת תרומת דם'), ('BLOOD_DISPENSED', 'ניפוק דם רגיל'), ('EMERGENCY_DISPENSED', 'ניפוק חירום'), ('DATA_EXPORTED', 'יצוא נתונים'), ('RECORD_VIEWED', 'צפייה ברשומה'), ('INVENTORY_CHECKED', 'בדיקת מלאי')], max_length=50)),
                ('user', models.CharField(default='system', max_length=200)),
                ('details', models.TextField()),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='audit_logs_action_31f574_idx'),
        ),
    ]
